Allow disabling tests with CATKIN_ENABLE_TESTING
ccny-ros-pkg/scan_tools pull request #90
Opened 2023-06-27 05:36 UTC by Smona

Most ROS packages now allow disabling test runs by setting `CATKIN_ENABLE_TESTING` to false. 

When I try to build `laser_scan_matcher` with `CATKIN_ENABLE_TESTING` set to false, I get this error:

```
CMake Error at /nix/store/y2dbjs0hpkdmra1jcnvih069nq27j9ka-ros-noetic-catkin-0.8.10-r1/share/catkin/cmake/test/tests.cmake:18 (message):
  () is not available when tests are not enabled.  The CMake code should only
  use it inside a conditional block which checks that testing is enabled:

  if(CATKIN_ENABLE_TESTING)

    (...)

  endif()

Call Stack (most recent call first):
  CMakeLists.txt:71 (add_rostest)
```

This PR just uses the recommended method to disable tests when the user requests it.

2023-06-27 09:27 UTC, 130s requested changes
- Making the test as an option makes sense to me. For developers' usecases they may not always want  to run tests.
   - I found `rostest.add_rostest` is a very strict so that can be even more strong motivation to disable the tests.
- I just merged CI change https://github.com/CCNYRoboticsLab/scan_tools/pull/88 (it was opened a while ago but had been unmerged) into `ros1` branch, the same branch this PR is aiming to. Would @Smona you mind enabling the tests in the CI config?

2023-06-27 09:33 UTC, 130s commented
Also do you mind @Smona cherry-picking the same changes into `ros2` branch? Nevermind if you do.

2023-07-05 04:14 UTC, Smona commented
Great, glad you are interested in merging this!

I've create a ros2 branch rebase of this in #90. I'm not sure what test configuration you're asking for, since my understanding is that `CATKIN_ENABLE_TESTING` is set to true by default.

2023-10-16 21:51 UTC, Smona commented
@130s i've merged in the CI check, but I think you need to approve the run.

2023-10-17 09:33 UTC, 130s approved these changes
Thanks for catching this up! Approving.
I'm not sure why CI has not run for this PR though, will see if it runs post-merge.

2023-10-17 09:33 UTC, merged